version: '3'
services:
  spark:
    image: jupyter/pyspark-notebook
    volumes:
      - ./data:/data
    ports:
      - "8888:8888"
  hadoop:
    image: sequenceiq/hadoop-docker:2.7.1
    ports:
      - "50070:50070"
